Amazing 2 bedroom, 1 bathroom house in Poughkeepsie. Amenities included: storage. Is cat friendly. Date Available: Nov 4th 2025. $1000/month rent. Utilities included: heat and water. Credit Check and Background Check Need. If you are interested
To schedule a showing, please reply via Craigslist with CONTACT Number.
